[project]
name = "uci-ensemble-uq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "probly>=0.3.1",
    "ruff>=0.15.0",
    "scikit-learn>=1.6,<1.7",
    "tabpfn>=2.0.3",
    "tabpfn-extensions[many-classes]>=0.0.4",
]
